spring:
  datasource:
    username: postgres
    password: Tsunami9
    driverClassName: org.postgresql.Driver
    driverDialect: org.hibernate.dialect.PostgreSQL82Dialect
    url: jdbc:postgresql://localhost/authservicedb
    hikari:
      minimum-idle: 1
      maximum-pool-size: 400


  cloud:
    stream:
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost
      bindings:
        kafka:
          binder:
            headers: version, action, EventVersion, EntityVersion
        user-event-input:
          destination: user-event
          contentType: application/json
          consumer:
            headerMode: raw

server:
  port: 8080

resteasy:
  deployment:
     async_job_service_enabled: true

keycloak:
  appRealm: chat
  idmBrokerAuthUrl: http://127.0.0.1:8080/auth
  idmBrokerApp: app-broker
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin